require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HeadsController do

  # This should return the minimal set of attributes required to create a valid
  # Head. As you add validations to Head, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    { "name" => "MyString" }
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # HeadsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all heads as @heads" do
      head = Head.create! valid_attributes
      get :index, {}, valid_session
      assigns(:heads).should eq([head])
    end
  end

  describe "GET show" do
    it "assigns the requested head as @head" do
      head = Head.create! valid_attributes
      get :show, {:id => head.to_param}, valid_session
      assigns(:head).should eq(head)
    end
  end

  describe "GET new" do
    it "assigns a new head as @head" do
      get :new, {}, valid_session
      assigns(:head).should be_a_new(Head)
    end
  end

  describe "GET edit" do
    it "assigns the requested head as @head" do
      head = Head.create! valid_attributes
      get :edit, {:id => head.to_param}, valid_session
      assigns(:head).should eq(head)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Head" do
        expect {
          post :create, {:head => valid_attributes}, valid_session
        }.to change(Head, :count).by(1)
      end

      it "assigns a newly created head as @head" do
        post :create, {:head => valid_attributes}, valid_session
        assigns(:head).should be_a(Head)
        assigns(:head).should be_persisted
      end

      it "redirects to the created head" do
        post :create, {:head => valid_attributes}, valid_session
        response.should redirect_to(Head.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved head as @head" do
        # Trigger the behavior that occurs when invalid params are submitted
        Head.any_instance.stub(:save).and_return(false)
        post :create, {:head => { "name" => "invalid value" }}, valid_session
        assigns(:head).should be_a_new(Head)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Head.any_instance.stub(:save).and_return(false)
        post :create, {:head => { "name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested head" do
        head = Head.create! valid_attributes
        # Assuming there are no other heads in the database, this
        # specifies that the Head created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Head.any_instance.should_receive(:update_attributes).with({ "name" => "MyString" })
        put :update, {:id => head.to_param, :head => { "name" => "MyString" }}, valid_session
      end

      it "assigns the requested head as @head" do
        head = Head.create! valid_attributes
        put :update, {:id => head.to_param, :head => valid_attributes}, valid_session
        assigns(:head).should eq(head)
      end

      it "redirects to the head" do
        head = Head.create! valid_attributes
        put :update, {:id => head.to_param, :head => valid_attributes}, valid_session
        response.should redirect_to(head)
      end
    end

    describe "with invalid params" do
      it "assigns the head as @head" do
        head = Head.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Head.any_instance.stub(:save).and_return(false)
        put :update, {:id => head.to_param, :head => { "name" => "invalid value" }}, valid_session
        assigns(:head).should eq(head)
      end

      it "re-renders the 'edit' template" do
        head = Head.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Head.any_instance.stub(:save).and_return(false)
        put :update, {:id => head.to_param, :head => { "name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested head" do
      head = Head.create! valid_attributes
      expect {
        delete :destroy, {:id => head.to_param}, valid_session
      }.to change(Head, :count).by(-1)
    end

    it "redirects to the heads list" do
      head = Head.create! valid_attributes
      delete :destroy, {:id => head.to_param}, valid_session
      response.should redirect_to(heads_url)
    end
  end

end
